name: Deploy Project
on: 
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
    paths-ignore:
      - '.github/worflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
        
      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build Project
        run:  npm run build

      - name: Deployment
        run: echo "Deploying ..."

  